github_username: dasaga26       # tu usuario de GitHub
title: "游늵 Mis m칠tricas de GitHub"
theme: radical                   # estilo visual

hide:
  - issues                       # ocultamos issues
  - prs                          # ocultamos pull requests

stats:
  - type: top-langs              # lenguajes m치s usados
    title: "Lenguajes m치s usados"
    limit: 6                     # m치ximo 6 lenguajes
  - type: commits                # commits totales
  - type: streak                 # racha de commits
  - type: repos                  # repositorios m치s activos
