name: Update Metrics

on:
    schedule:
        - cron: "0 0 * * *" # se ejecuta todos los días a medianoche
    workflow_dispatch: # permite ejecutarlo manualmente

permissions:
    contents: write # Permiso para escribir en el repositorio

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Generate Metrics
              uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  filename: metrics.svg

                  # Configuración base
                  base: header, activity, community, repositories, metadata

                  # Plugin de lenguajes más usados
                  plugin_languages: yes
                  plugin_languages_limit: 8
                  plugin_languages_sections: most-used
                  plugin_languages_colors: github
                  plugin_languages_threshold: 0%
