name: Update Metrics

on:
  schedule:
    - cron: '0 0 * * *'   # se ejecuta todos los días
  workflow_dispatch:       # permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Metrics
        uses: lowlighter/metrics@v3
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
