name: Update Metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'   # se ejecuta todos los días
  workflow_dispatch:       # permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
